### ISSUE TITLE
Defragment the file system (not files)

### ISSUE THREAD

**Issue by zvezdochiot** [vbmacher/defrag#1]
It is interesting to defragment the file tables (FAT32) without defragmenting the files themselves.

**Comment by vbmacher** [comment]
Hi, the project is dead for several years now, and I don't plan to continue on it.

Anyway, how would you defrag "just filesystem"? FAT is a map of clusters, or "array", in which each item corresponds to a specific cluster. It's index is a cluster number, and the value is a next cluster number (simplified explanation). You can't move values in FAT table without actually copying data.

Secondly, what outcome you would gain from it? FAT table is very small compared to data area, so it is usually read as a whole by operating system. Each file cluster chain is a linked list, where an item points to another, so the next item is accessed in O(1) anyway.

**Comment by zvezdochiot** [comment]
In fact, I do not need a defragmenter. I need to re-create the file table from scratch. Using the existing file table as a sample. But there are no such utilities. Therefore, I am looking for a "bicycle".
