### ISSUE TITLE
Doesn't build on Arch Linux

### ISSUE THREAD

**Issue by Cthutu** [vbmacher/defrag#2]
Here are the results of make:

```
gcc -Iinclude -O0 -fshort-enums -g -o defrag analyze.o defrag.o disk.o entry.o fat32.o; \
xgettext -d f32id_loc -s -o f32id_loc.pot analyze.c defrag.c disk.c entry.c fat32.c
/usr/bin/ld: defrag.o:/home/matt/repos/defrag/defrag.c:39: multiple definition of `entryCount'; analyze.o:/home/matt/repos/defrag/analyze.c:58: first defined here
collect2: error: ld returned 1 exit status
```

**Comment by Cthutu** [comment]
I solved it by making both lines static.

**Comment by vbmacher** [comment]
Hi @Cthutu, thanks for posting this ticket! I use Fedora, but I can still reproduce the issue. The project is veeeery old, from my school times, and the code is also not really clean :)

I just renamed the `entryCount` in `analyze.c` to `an_entryCount` and also fixed other warnings. I hope it will work for you :)
